---
abstract: 'Assemble multiple Regular Expressions into a single RE'
author:
  - 'David Landgren'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Regexp-Assemble
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '1.001014'
  Test::Pod: '1.48'
  constant: '0'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  repository: https://github.com/ronsavage/Regexp-Assemble.git
version: '0.36'
